sudo: required

language: c

compiler: gcc

before_script:
        - cmake .

script:
        - make -j 4

after_script:
        - ./linked_list/singly/bin/slist_main
        - ./linked_list/circular/bin/clist_main
        - ./stack/bin/stack_main
        - ./queue/bin/queue_main

notifications:
        email:
            - jwhu1024@gmail.com
                          
        on_success: change
        on_failure: always
