sudo: required

language: c

compiler: gcc

#before_install:
#        - sudo apt-get -qq update
#        - sudo apt-get install alsa-utils

before_script:
        - cd linked_list/singly
	- cmake .
script:
        - make -j 4

after_script:
        - ./bin/slist_main

notifications:
        email:
            - jwhu1024@gmail.com
                          
        on_success: change
        on_failure: always

